### ISSUE TITLE
Verificar correcto encoding

### ISSUE THREAD

**Issue by dsbarrionuevo** [Gochip/HardwareCollector#2]
Verificar enconding en captura de información de los clientes, manejo en el servidor, y envío por TCP.

**Comment by milyzc** [comment]
Los dos cliente envían los datos en ascii al servidor y cuando reciben datos los codifican a ascii. Ambos clientes tiene un tamaño de buffer para recibir de 1024 bytes. Los tres proyecto tienen un encoding="utf-8".
